default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  user: <%= ENV["DB_USER"] %>
  password: <%= ENV["DB_PASS"] %>

development:
  <<: *default
  database: feedreader_dev

test:
  <<: *default
  database: feedreader_test

production:
  <<: *default
  database: feedreader_prod
